# Generated by Django 6.1 on 2026-09-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('fingerprint', models.JSONField(default=list)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.repo')),
            ],
        ),
    ]
