# Generated by Django 6.1 on 2026-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_similaritymatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='clone_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
